version: 0.0
os: linux
files:
  - source: scripts/start_container.sh
    destination: /opt/codedeploy-agent/deployment-root/
hooks:
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
